[workspace]
authors = ["thomashopkins32 <thopkins1@bnl.gov>"]
channels = ["conda-forge"]
name = "nslsii"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.10,<3.15"
redis-py = ">=7.1.0,<8"

[pypi-dependencies]
nslsii = { path = ".", editable = true }
